### PR TITLE
reference: Add Color

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
I can't find the laDefense.jpg...

```Java
PImage img;
img = loadImage("laDefense.jpg");
background(img);
```

**Comment by jeremydouglass** [comment]
Was the issue with laDefense.jpg ever resolved?

https://github.com/processing/processing-docs/search?utf8=%E2%9C%93&q=laDefense.jpg&type=

If not, submit the question to processing-docs issues.

**Comment by jeremydouglass** [comment]
Did you ever find laDefense.jpg? If not, did you submit an issue to processing-docs?

**Comment by gaocegege** [comment]
I haven't. OK, I will file an issue.

**Comment by jeremydouglass** [comment]
Great, thanks!

If we don't have it, are we also skipping the end-to-end tests on examples that would use it? e.g. background:

-  examples/reference/background/background3/background3.rpde
-  https://processing-r.github.io/reference/background.html

**Pull request merged**
