### PR TITLE
Support Processing libraries

### PR DESCRIPTION
**Pull request by gaocegege**
```R
P3D <- "processing.opengl.PGraphics3D"

settings <- function() {
    size(200, 200, P3D)
}

setup <- function() {
    cam = PeasyCam$new(processing, 100)
    cam$setMinimumDistance(50)
    cam$setMaximumDistance(500)
}

draw <- function() {
    rotateX(-.5)
    rotateY(-.5)
    background(0)
    fill(255, 0, 0)
    box(30)
    pushMatrix()
    translate(0, 0, 20)
    fill(0, 0, 255)
    box(5)
    popMatrix()
}
```

The code works but now it is an ad-hoc implementation: https://github.com/gaocegege/Processing.R/pull/133/files#diff-914114bed9183352c9f4543df165fccbR48

Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
It works in PDE but fails in Runner, I will update the issue #133

**Comment by jeremydouglass** [comment]
I'm not seeing any results when I pull the latest master, open a new sketch, and run the example given above. I have peasycam installed in the default location in libraries using the PDE Contributions Manager.

Are there other required steps, such as manually adding the peasycam library folder into the sketch?

**Comment by gaocegege** [comment]
No, I don't think so. It will import all libraries, I will have a try in a clean environment.

**Comment by gaocegege** [comment]
I found the reason:

> The code works but now it is an ad-hoc implementation: https://github.com/gaocegege/Processing.R/pull/133/files#diff-914114bed9183352c9f4543df165fccbR48

**Comment by jeremydouglass** [comment]
Ha! Yes, a hard-coded path would do it.

**Pull request merged**
