### PR TITLE
Pop error or exception to PDE

### LINKED ISSUE #24: Redirect STDERR to Processing console
Now it is full of bugs, some logs in Processing.R will redirect to Processing console, it is confusing to users.

### PR DESCRIPTION
**Pull request by gaocegege**
Close #24

We should redirect the exception into PDE.

Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by jeremydouglass** [comment]
Yes, redirecting to PDE is a good idea (no popup).

Note that 3.3.4 currently has a regression bug with console output -- so test against 3.3.3 or wait for a fix:

https://github.com/processing/processing/issues/5110

**Comment by gaocegege** [comment]
Thanks for the information!

**Comment by gaocegege** [comment]
It is weird that renjin does't throw a exception when it should, for example, `renjin.eval('p')` and there is no p at all in R scope :thinking:

**Comment by gaocegege** [comment]
The logic is a little more complex since there are some new errors, sucd as package download error

**Comment by gaocegege** [comment]
image

Now the exceptions be will shown in the PDE, but it could not show the line and column.

**Comment by gaocegege** [comment]
The implementation imports a new bug: #143 

The bug also exists in Python mode, I have filed a new issue about it.

**Pull request merged**
