### PR TITLE
demo: Add a demo

### PR DESCRIPTION
**Pull request by gaocegege**
ref https://www.openprocessing.org/sketch/377464

Just for fun

Delay until #97 
Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by jeremydouglass** [comment]
Tested this, and it ran fine. Nice adaptation of the reference sketch -- your original wobbly ellipse phase is  particularly fun.

Remind me: why is:

    radians = RLangPApplet$radians

...something that must be defined in `src/rprocessing/r/core.R` -- why can it not simply be added to the top of `FiguresTransformation.rpde` as a local definition? I know that it does not work, but what is the explanation?

**Comment by gaocegege** [comment]
I think it is caused by our policy to eval the code, but I am not sure the specific reason. :thinking:

**Comment by jeremydouglass** [comment]
Could this be resolved now that #97 has a functional workaround?

**Comment by gaocegege** [comment]
Yeah, I will refactor the code and merge it.

**Pull request merged**
