### PR TITLE
coala: Add coala support

### LINKED ISSUE #52: adopt style guide for R code and examples
All R example code and documentation should largely conform to some consistent R code style guide -- ideally one that already exists, rather than the project developing its own.

Here is one example:

-  Google's R Style Guide https://google.github.io/styleguide/Rguide.xml

Future documentation efforts would:

- [x] choose an R style guide
- [x] reference the chosen style guide in the wiki / documentation
- [x] correct issues of style in example code to conform

----

Example style consistency will be especially useful because some Processing.R users are more likely to be confused by readability issues, and may also be learning R syntax for the first time by way of Processing.

### PR DESCRIPTION
**Pull request by gaocegege**
Closes #52 
Ref https://github.com/coala/coala-bears/issues/1750

Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
coala is a perfect tool to lint and format the code in command line. But it seems that there is something wrong. I will comment the checkstyle bear now and uncomment it until the bug is fixed.

**Comment by jeremydouglass** [comment]
Excellent! Good use of coala to clean up the example sketches.

Please create an Issue for the checkstyle bear issue that references the appropriate commit line.

Please clarify what "add coala support" means -- give a bit more detail here and in the log file. For example, it could mean support for running coala manually against the repo, or support for Travis-ci integration of coala, or support for invoking coala from PDE. This will help non-core developers understand how they could use coala with Processing.R

**Comment by gaocegege** [comment]
#67 has been filed :) And I have added the introduction in #68 , I think it is better to add the detail into the documentation :thinking: 

WDYT

**Comment by jeremydouglass** [comment]
Good -- yes, I think the Coding Style section is the best place for it.

Good inclusion of references, e.g. to FormatR. Is the coala add.r module based on FormatR, and/or is it designed to follow the same rules?

**Comment by gaocegege** [comment]
Yes, the FormatRBear uses formatR as the backend.

> ## FormatRBear
> Check and correct formatting of R Code using known formatR utility.

**Pull request merged**
