### PR TITLE
core.R: Add colorMode specific constants

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by jeremydouglass** [comment]
Nice addition.

Why was adding the constants combined with dropping casting for colorMode? Is the idea that users should *only* use the constants?

**Comment by jeremydouglass** [comment]
Also:

The complete list of PConstants are here:

https://github.com/processing/processing/blob/master/core/src/processing/core/PConstants.java

Is there any reason not to simply add ALL of them to src/rprocessing/r/core.R at one time, rather than adding them one by one as we look at support for different features?

**Comment by gaocegege** [comment]
I am not sure if all of these are built-in in PDE.

**Comment by jeremydouglass** [comment]
They are ALL built in to PDE. PConstants is an interface, and PDE Java mode implements that interface.

The only ones worth leaving out are the few marked `@Deprecated`.

You can inspect the output from the first few if you want by printing each one in a PDE(Java) sketch ... but they are all there.

```
println(X); // int X = 0;
println(Y); // int Y = 1;
println(Z); // int Z = 2;

println(JAVA2D); // String JAVA2D = "processing.awt.PGraphicsJava2D";
println(P2D   ); // String P2D = "processing.opengl.PGraphics2D";
println(P3D   ); // String P3D = "processing.opengl.PGraphics3D";
println(OPENGL); // String OPENGL = P3D;
println(FX2D  ); // String FX2D = "processing.javafx.PGraphicsFX2D";
println(PDF   ); // String PDF = "processing.pdf.PGraphicsPDF";
println(SVG   ); // String SVG = "processing.svg.PGraphicsSVG";
println(DXF   ); // String DXF = "processing.dxf.RawDXF";

println(OTHER  ); // int OTHER   = 0;
println(WINDOWS); // int WINDOWS = 1;
println(MACOSX ); // int MACOSX  = 2;
println(LINUX  ); // int LINUX   = 3;

println(EPSILON  ); // float EPSILON = 0.0001f;
for(String s:platformNames){ println(s); } // String[] platformNames = { "other", "windows", "macosx", "linux" };

println(MAX_FLOAT); // float MAX_FLOAT = Float.MAX_VALUE;
println(MIN_FLOAT); // float MIN_FLOAT = -Float.MAX_VALUE;
println(MAX_INT  ); // int MAX_INT = Integer.MAX_VALUE;
println(MIN_INT  ); // int MIN_INT = Integer.MIN_VALUE;

println(VERTEX            ); // int VERTEX = 0;
println(BEZIER_VERTEX     ); // int BEZIER_VERTEX = 1;
println(QUADRATIC_VERTEX  ); // int QUADRATIC_VERTEX = 2;
println(CURVE_VERTEX      ); // int CURVE_VERTEX = 3;
println(BREAK             ); // int BREAK = 4;
println(QUAD_BEZIER_VERTEX); // int QUAD_BEZIER_VERTEX = 2;  // should not have been exposed

println(PI        ); // float PI = (float) Math.PI;
println(HALF_PI   ); // float HALF_PI = (float) (Math.PI / 2.0);
println(THIRD_PI  ); // float THIRD_PI = (float) (Math.PI / 3.0);
println(QUARTER_PI); // float QUARTER_PI = (float) (Math.PI / 4.0);
println(TWO_PI    ); // float TWO_PI = (float) (2.0 * Math.PI);
println(TAU       ); // float TAU = (float) (2.0 * Math.PI);

println(DEG_TO_RAD ); // float DEG_TO_RAD = PI/180.0f;
println(RAD_TO_DEG ); // float RAD_TO_DEG = 180.0f/PI;

println(WHITESPACE ); // String WHITESPACE = " \t\n\r\f\u00A0";

println(RGB   ); // int RGB   = 1;  // image & color
println(ARGB  ); // int ARGB  = 2;  // image
println(HSB   ); // int HSB   = 3;  // color
println(ALPHA ); // int ALPHA = 4;  // image

println(TIFF ); // int TIFF  = 0;
println(TARGA); // int TARGA = 1;
println(JPEG ); // int JPEG  = 2;
println(GIF  ); // int GIF   = 3;

```

**Comment by gaocegege** [comment]
OK got it! I will add them all

**Pull request merged**
