### PR TITLE
Support Package in R

### LINKED ISSUE #17: Support packages (libraries) in R
Renjin [supports some of CRAN and BioConductor R libraries](http://packages.renjin.org/), Processing.R could benefit from it.

ref [the post in forum](https://forum.processing.org/two/discussion/comment/91251/#Comment_91251)

> As for libraries, I did a feasibility study. Renjin is used in Processing.R as the backend to interpret R code in JVM. [Documentation in renjin.org](http://docs.renjin.org/en/latest/interactive/index.html#using-packages) shows differences about packages between GNU R and renjin. 
>
>It [supports some of CRAN and BioConductor R libraries](http://packages.renjin.org/) and I want to integrate those libraries into Processing.R in GSoC. But I'm not sure whether those packages could be installed in runtime or ahead of time.
>
>BTW I think Jython supports those libraries which do not require C compilation, although I do not have the experience on it.

### PR DESCRIPTION
**Pull request by gaocegege**
Close #17 

Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by jeremydouglass** [comment]
This adding plyr should probably be accompanied by a test sketch for loading plyr -- even if the test sketch currently fails.

**Comment by gaocegege** [comment]
I am not sure if I understand you 🤔 

Could you give me more details?

**Comment by gaocegege** [comment]
I want to follow what renjin-cli does: create a package loader and set it into the renjin, then install the packages JIT.

**Comment by gaocegege** [comment]
Try to use maven deps task in ant: https://stackoverflow.com/questions/1422427/is-there-a-way-i-can-use-maven-repositories-to-add-dependencies-to-ant

**Comment by gaocegege** [comment]
```R
library(foreach)

foreach(i=1:3) %do%
sqrt(i)
```

I have imported all deps into ant's lib directory, and it works. But the approach has some drawbacks:

1. Recompile and reinstall the mode when there is a new library to be imported.
2. The size of the mode is definitely large.

I will try to add maven dep directory into path, install the R package and load the package into classloader in runtime

**Comment by gaocegege** [comment]
Now Processing.R could use R packages in local maven repository directory (.m2) thanks to maven-ant-tasks and renjin-cli. I will try to implement the logic about automatic installation of R library.

**Comment by gaocegege** [comment]
We have a problem: [gcc-bridge- plugin] only have the jar for X86_64, but the architecture in AppVeyor is X86.

**Comment by jeremydouglass** [comment]
Is this a Processing.R implementation problem -- or just a problem for the
configuration of continuous integration?

I've taken a quick look at gcc-bridge, but still need to come up to speed.
Might be worth a renjin forum search and question:

-  http://www.renjin.org/blog/2016-01-31-introducing-gcc-bridge.html
-  https://github.com/bedatadriven/renjin/tree/master/tools/gcc-bridge
-
https://groups.google.com/forum/#!searchin/renjin-dev/gcc-bridge%7Csort:relevance

**Comment by gaocegege** [comment]
It is caused by renjin. the plugin is a dependency by renjin, and it only has gcc-bridge-plugin-linux-x86_64.jar. AppVeyor's machine is x86, so it fails to download this dependency.

**Comment by jeremydouglass** [comment]
What are the alternatives here?

Is there a 32-bit x86 version of gcc-bridge?

Alternately, would using the 64-bit version of gcc-bridge (and changing the AppVeyor target machine to 64 bit) make Processing.R mode available for x86-64_bit machines only?

**Comment by gaocegege** [comment]
Actually I have no idea now, I want to implement the feature in x86_64, then I will try to find a solution for x86 arch.

**Comment by gaocegege** [comment]
Now Processing.R could download the packages automatically, but there is no progress output in console, we should let users know the progress.

**Comment by gaocegege** [comment]
As for the problem in AppVeyor, I will try the x86_64 version in x86 arch. I have no idea how to deal with it :thinking:

**Comment by jeremydouglass** [comment]
Re: Now Processing.R could download the packages automatically, but there is no progress output in console, we should let users know the progress.

You should ask @jdf if/how Processing.py thought about dealing with similar issues with python libraries.

**Comment by gaocegege** [comment]
re @jeremydouglass 

I know how to do but it will take some time. renjin is a good reference for us.

**Comment by jdf** [comment]
Python Mode has no design at all for installing Python libraries.

**Pull request merged**
