### PR TITLE
reference: Migrate property from processing.py

### PR DESCRIPTION
**Pull request by gaocegege**
I write a python script to migrate the docs from processing.py

### CODE REVIEW

**Comment by jeremydouglass** [comment]
Where is this script getting materials from?

-  https://github.com/jdf/processing.py
-  https://github.com/kazimuth/processing-py-site

**Comment by gaocegege** [comment]
https://github.com/kazimuth/processing-py-site/tree/master/Reference/api_en

And it is a one-time script, I think we won't run it again.

**Comment by jeremydouglass** [comment]
Got it. So is the idea to use an XML-based format after all instead of YML?

**Comment by gaocegege** [comment]
Yeah!

**Pull request merged**
