### PR TITLE
Fix the code style according to coala

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <ce.gao@outlook.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
I have imported google style formatter into the eclispse but there are soooo many issues reported by coala: https://pastebin.com/rN8mN0Tj.

And there is some weird thing: https://github.com/google/styleguide/issues/248

**Comment by jeremydouglass** [comment]
I'll edit this comment later -- but let's discuss potentially disabling or reconfiguring ParameterName:

32| ··public·void·point(double·x,·double·y)·{
|    | [NORMAL] CheckstyleBear (ParameterName):
|    | Parameter name 'x' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'.

**Comment by gaocegege** [comment]
https://pastebin.com/3Rp8iXDY

English version

**Comment by gaocegege** [comment]
There are 92 issues about Java Doc, and 90 issues about import order. The total number is 173.

**Comment by gaocegege** [comment]
I have removed import order check and javadoc check, because it causes so many errors

**Pull request merged**
