### PR TITLE
Add Unit Test Cases

### PR DESCRIPTION
**Pull request by gaocegege**

### CODE REVIEW

**Comment by gaocegege** [comment]
ref #10

**Comment by jeremydouglass** [comment]
Codacy looks good -- I hope it is helpful.

Have you worked using TDD in the past, and are you planning on writing unit tests as part of your development workflow?

Keep in mind that, for a project like this, a very practical model of testing is a large collection of simple reference sketches that either compile and run or fail. Many of the simple reference examples for Processing functions/methods -- once translated into R -- can also be sketches that serve as test cases (although you need to rig them up to count as runable tests for coverage reports).

**Comment by gaocegege** [comment]
Yep. I have tried BDD and TDD in the past. But there are some difficulties when it comes to Processing.R.

Actually I have no idea how to test Processing.R. Unit test is not enough, I don't know much about UI test. Is there any documentation about the test in Processing?

**Comment by jeremydouglass** [comment]
> Is there any documentation about the tests in Processing?

I'm not too familiar with unit tests or other testing in Processing core, although I know where some testing code is. This strikes me as a good open discussion for the forum. I'll start a thread there.

**Comment by gaocegege** [comment]
OK, I have one English writing exam this week, so maybe I don't have much time on Processing.R. But I will sync the thread as I can.

**Comment by jeremydouglass** [comment]
Good, and don't forget: you don't have to spend *any* time on it -- GSOC doesn't start until after May 30! Good luck with your exam.

**Comment by gaocegege** [comment]
:smile:  Got it.

**Pull request merged**
