### PR TITLE
reference: Add the missing images

### PR DESCRIPTION
**Pull request by gaocegege**

### CODE REVIEW

**Comment by gaocegege** [comment]
The alien does not look like a normal alien. :thinking: 

```java
PShape alien, head, body;

void setup() {
  size(100, 100);

  // Create the shape group
  alien = createShape(GROUP);

  // Make two shapes
  head = createShape(ELLIPSE, -25, 0, 50, 50);
  head.setFill(color(255));
  body = createShape(RECT, -25, 45, 50, 40);
  body.setFill(color(0));

  // Add the two "child" shapes to the parent group
  alien.addChild(body);
  alien.addChild(head);
}

void draw() {
  background(204);
  translate(50, 15);
  shape(alien); // Draw the group
}
```

**Comment by jeremydouglass** [comment]
Great work! Working through these details and fixing small issues is really making it clear how powerful and flexible Processing.R is.

**Comment by gaocegege** [comment]
@jeremydouglass Could you take a look at the fourth example in https://processing.org/reference/createShape_.html, I think it is weird.

**Comment by jeremydouglass** [comment]
You are right, that looks really weird.

I doubt this is how the example was supposed to look. Either the example was edited incorrectly, or the PShape code changed and broke the example.

Hmm. I recall some changes to PShape transformations that occurred in https://github.com/processing/processing/issues/4662 -- I wonder if this is a bug and something around that change introduced it error?

... no, this example code just looks wrong. I don't understand how these coordinates would generate a connected head and body, even with rectMode(CENTER) or the second child shape being positioned relative to the first. Also not sure how the circle/rect is an "alien."

Perhaps this is what was intended? Take a look -- I'm thinking maybe open another processing-docs issue.

```
PShape alien, head, body;

void setup() {
  size(100, 100);

  // Create the shape group
  alien = createShape(GROUP);

  // Make two shapes
  head = createShape(ELLIPSE, 0, 0, 50, 50);
  head.setFill(color(255));
  body = createShape(RECT, -25, 0, 50, 50);
  body.setFill(color(0));

  // Add the two "child" shapes to the parent group
  alien.addChild(body);
  alien.addChild(head);
}

void draw() {
  background(204);
  translate(width/2, height/2);
  shape(alien); // Draw the group
}
```

**Comment by jeremydouglass** [comment]
Let's use our own corrected sketch and our own image.

Also, report the image not matching the "alien" head-body to: processing-docs/issues

**Pull request merged**
